package com.hkperf;
// Generated Aug 2, 2013 12:11:08 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ResponseDetails generated by hbm2java
 */
@Entity
@Table(name="response_details")
public class ResponseDetails  implements java.io.Serializable {


 
    @Id
    
    @Column(name="idresponse_details", unique=true, nullable=false)
    private int idresponseDetails;
 
    
    @Column(name="request_id")
    private int requestId;

    @Column(name="response_view_type", length=45)
    private String responseViewType;
 
    
    @Column(name="load_time")
    private String loadTime;
 
    
    @Column(name="speedIndex", length=45)
    private String speedIndex;
 
    
    @Column(name="ttfb", length=45)
    private String ttfb;
 
    
    @Column(name="url", length=45)
    private String url;
 
    
    @Column(name="visuallyCompleteDT", length=45)
    private String visuallyCompleteDt;
 
    
    @Column(name="adult_site", length=45)
    private String adultSite;
 
    
    @Column(name="aft", length=45)
    private String aft;
 
    
    @Column(name="avgRun", length=45)
    private String avgRun;
 
    
    @Column(name="base_page_cdn", length=45)
    private String basePageCdn;
 
    
    @Column(name="browser_name", length=45)
    private String browserName;
 
    
    @Column(name="browser_version", length=45)
    private String browserVersion;
 
    
    @Column(name="bytesIn", length=45)
    private String bytesIn;
 
    
    @Column(name="bytesInDoc", length=45)
    private String bytesInDoc;
 
    
    @Column(name="bytesOutDoc", length=45)
    private String bytesOutDoc;
 
    
    @Column(name="cached", length=45)
    private String cached;
 
    
    @Column(name="connections", length=45)
    private String connections;
 
    
    @Column(name="dt", length=45)
    private String date;
 
    
    @Column(name="docTime", length=45)
    private String docTime;
 
    
    @Column(name="domContentLoadedEventEnd", length=45)
    private String domContentLoadedEventEnd;
 
    
    @Column(name="domContentLoadedEventStart", length=45)
    private String domContentLoadedEventStart;
 
    
    @Column(name="domElements", length=45)
    private String domElements;
 
    
    @Column(name="domTime", length=45)
    private String domTime;
 
    
    @Column(name="firstPaint", length=45)
    private String firstPaint;
 
    
    @Column(name="fixed_viewport", length=45)
    private String fixedViewport;
 
    
    @Column(name="fullyLoaded", length=45)
    private String fullyLoaded;
 
    
    @Column(name="gzip_savings", length=45)
    private String gzipSavings;
 
    
    @Column(name="gzip_total", length=45)
    private String gzipTotal;
 
    
    @Column(name="image_savings", length=45)
    private String imageSavings;
 
    
    @Column(name="image_total", length=45)
    private String imageTotal;
 
    
    @Column(name="lastVisualChange", length=45)
    private String lastVisualChange;
 
    
    @Column(name="loadEventEnd", length=45)
    private String loadEventEnd;
 
    
    @Column(name="loadEventStart", length=45)
    private String loadEventStart;
 
    
    @Column(name="loadTime", length=45)
    private String loadTime_1;
 
    
    @Column(name="minify_savings", length=45)
    private String minifySavings;
 
    
    @Column(name="minify_total", length=45)
    private String minifyTotal;
 
    
    @Column(name="optimization_checked", length=45)
    private String optimizationChecked;
 
    
    @Column(name="pageSpeedVersion", length=45)
    private String pageSpeedVersion;
 
    
    @Column(name="render", length=45)
    private String render;
 
    
    @Column(name="requests", length=45)
    private String requests;
 
    
    @Column(name="requestsDoc", length=45)
    private String requestsDoc;
 
    
    @Column(name="responses_200", length=45)
    private String responses200;
 
    
    @Column(name="responses_404", length=45)
    private String responses404;
 
    
    @Column(name="responses_other", length=45)
    private String responsesOther;
 
    
    @Column(name="result", length=45)
    private String result;
 
    
    @Column(name="score_cdn", length=45)
    private String scoreCdn;
 
    
    @Column(name="score_combine", length=45)
    private String scoreCombine;
 
    
    @Column(name="score_compress", length=45)
    private String scoreCompress;
 
    
    @Column(name="score_cookies", length=45)
    private String scoreCookies;
 
    
    @Column(name="score_etags", length=45)
    private String scoreEtags;
 
    
    @Column(name="score_gzip", length=45)
    private String scoreGzip;
 
    
    @Column(name="score_keep_alive", length=45)
    private String scoreKeepAlive;
 
    
    @Column(name="score_minify", length=45)
    private String scoreMinify;
 
    
    @Column(name="score_progressive_jpeg", length=45)
    private String scoreProgressiveJpeg;
 
    
    @Column(name="server_count", length=45)
    private String serverCount;
 
    
    @Column(name="server_rtt", length=45)
    private String serverRtt;
 
    
    @Column(name="title", length=45)
    private String title;
 
    
    @Column(name="titleTime", length=45)
    private String titleTime;
 
    
    @Column(name="visualComplete", length=45)
    private String visualComplete;
   
    public int getIdresponseDetails() {
        return this.idresponseDetails;
    }
    
    public void setIdresponseDetails(int idresponseDetails) {
        this.idresponseDetails = idresponseDetails;
    }
    public int getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(int requestId) {
        this.requestId = requestId;
    }

    public String getResponseViewType() {
        return this.responseViewType;
    }
    
    public void setResponseViewType(String responseViewType) {
        this.responseViewType = responseViewType;
    }
    public String getLoadTime() {
        return this.loadTime;
    }
    
    public void setLoadTime(String loadTime) {
        this.loadTime = loadTime;
    }
    public String getSpeedIndex() {
        return this.speedIndex;
    }
    
    public void setSpeedIndex(String speedIndex) {
        this.speedIndex = speedIndex;
    }
    public String getTtfb() {
        return this.ttfb;
    }
    
    public void setTtfb(String ttfb) {
        this.ttfb = ttfb;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getVisuallyCompleteDt() {
        return this.visuallyCompleteDt;
    }
    
    public void setVisuallyCompleteDt(String visuallyCompleteDt) {
        this.visuallyCompleteDt = visuallyCompleteDt;
    }
    public String getAdultSite() {
        return this.adultSite;
    }
    
    public void setAdultSite(String adultSite) {
        this.adultSite = adultSite;
    }
    public String getAft() {
        return this.aft;
    }
    
    public void setAft(String aft) {
        this.aft = aft;
    }
    public String getAvgRun() {
        return this.avgRun;
    }
    
    public void setAvgRun(String avgRun) {
        this.avgRun = avgRun;
    }
    public String getBasePageCdn() {
        return this.basePageCdn;
    }
    
    public void setBasePageCdn(String basePageCdn) {
        this.basePageCdn = basePageCdn;
    }
    public String getBrowserName() {
        return this.browserName;
    }
    
    public void setBrowserName(String browserName) {
        this.browserName = browserName;
    }
    public String getBrowserVersion() {
        return this.browserVersion;
    }
    
    public void setBrowserVersion(String browserVersion) {
        this.browserVersion = browserVersion;
    }
    public String getBytesIn() {
        return this.bytesIn;
    }
    
    public void setBytesIn(String bytesIn) {
        this.bytesIn = bytesIn;
    }
    public String getBytesInDoc() {
        return this.bytesInDoc;
    }
    
    public void setBytesInDoc(String bytesInDoc) {
        this.bytesInDoc = bytesInDoc;
    }
    public String getBytesOutDoc() {
        return this.bytesOutDoc;
    }
    
    public void setBytesOutDoc(String bytesOutDoc) {
        this.bytesOutDoc = bytesOutDoc;
    }
    public String getCached() {
        return this.cached;
    }
    
    public void setCached(String cached) {
        this.cached = cached;
    }
    public String getConnections() {
        return this.connections;
    }
    
    public void setConnections(String connections) {
        this.connections = connections;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getDocTime() {
        return this.docTime;
    }
    
    public void setDocTime(String docTime) {
        this.docTime = docTime;
    }
    public String getDomContentLoadedEventEnd() {
        return this.domContentLoadedEventEnd;
    }
    
    public void setDomContentLoadedEventEnd(String domContentLoadedEventEnd) {
        this.domContentLoadedEventEnd = domContentLoadedEventEnd;
    }
    public String getDomContentLoadedEventStart() {
        return this.domContentLoadedEventStart;
    }
    
    public void setDomContentLoadedEventStart(String domContentLoadedEventStart) {
        this.domContentLoadedEventStart = domContentLoadedEventStart;
    }
    public String getDomElements() {
        return this.domElements;
    }
    
    public void setDomElements(String domElements) {
        this.domElements = domElements;
    }
    public String getDomTime() {
        return this.domTime;
    }
    
    public void setDomTime(String domTime) {
        this.domTime = domTime;
    }
    public String getFirstPaint() {
        return this.firstPaint;
    }
    
    public void setFirstPaint(String firstPaint) {
        this.firstPaint = firstPaint;
    }
    public String getFixedViewport() {
        return this.fixedViewport;
    }
    
    public void setFixedViewport(String fixedViewport) {
        this.fixedViewport = fixedViewport;
    }
    public String getFullyLoaded() {
        return this.fullyLoaded;
    }
    
    public void setFullyLoaded(String fullyLoaded) {
        this.fullyLoaded = fullyLoaded;
    }
    public String getGzipSavings() {
        return this.gzipSavings;
    }
    
    public void setGzipSavings(String gzipSavings) {
        this.gzipSavings = gzipSavings;
    }
    public String getGzipTotal() {
        return this.gzipTotal;
    }
    
    public void setGzipTotal(String gzipTotal) {
        this.gzipTotal = gzipTotal;
    }
    public String getImageSavings() {
        return this.imageSavings;
    }
    
    public void setImageSavings(String imageSavings) {
        this.imageSavings = imageSavings;
    }
    public String getImageTotal() {
        return this.imageTotal;
    }
    
    public void setImageTotal(String imageTotal) {
        this.imageTotal = imageTotal;
    }
    public String getLastVisualChange() {
        return this.lastVisualChange;
    }
    
    public void setLastVisualChange(String lastVisualChange) {
        this.lastVisualChange = lastVisualChange;
    }
    public String getLoadEventEnd() {
        return this.loadEventEnd;
    }
    
    public void setLoadEventEnd(String loadEventEnd) {
        this.loadEventEnd = loadEventEnd;
    }
    public String getLoadEventStart() {
        return this.loadEventStart;
    }
    
    public void setLoadEventStart(String loadEventStart) {
        this.loadEventStart = loadEventStart;
    }
    public String getLoadTime_1() {
        return this.loadTime_1;
    }
    
    public void setLoadTime_1(String loadTime_1) {
        this.loadTime_1 = loadTime_1;
    }
    public String getMinifySavings() {
        return this.minifySavings;
    }
    
    public void setMinifySavings(String minifySavings) {
        this.minifySavings = minifySavings;
    }
    public String getMinifyTotal() {
        return this.minifyTotal;
    }
    
    public void setMinifyTotal(String minifyTotal) {
        this.minifyTotal = minifyTotal;
    }
    public String getOptimizationChecked() {
        return this.optimizationChecked;
    }
    
    public void setOptimizationChecked(String optimizationChecked) {
        this.optimizationChecked = optimizationChecked;
    }
    public String getPageSpeedVersion() {
        return this.pageSpeedVersion;
    }
    
    public void setPageSpeedVersion(String pageSpeedVersion) {
        this.pageSpeedVersion = pageSpeedVersion;
    }
    public String getRender() {
        return this.render;
    }
    
    public void setRender(String render) {
        this.render = render;
    }
    public String getRequests() {
        return this.requests;
    }
    
    public void setRequests(String requests) {
        this.requests = requests;
    }
    public String getRequestsDoc() {
        return this.requestsDoc;
    }
    
    public void setRequestsDoc(String requestsDoc) {
        this.requestsDoc = requestsDoc;
    }
    public String getResponses200() {
        return this.responses200;
    }
    
    public void setResponses200(String responses200) {
        this.responses200 = responses200;
    }
    public String getResponses404() {
        return this.responses404;
    }
    
    public void setResponses404(String responses404) {
        this.responses404 = responses404;
    }
    public String getResponsesOther() {
        return this.responsesOther;
    }
    
    public void setResponsesOther(String responsesOther) {
        this.responsesOther = responsesOther;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public String getScoreCdn() {
        return this.scoreCdn;
    }
    
    public void setScoreCdn(String scoreCdn) {
        this.scoreCdn = scoreCdn;
    }
    public String getScoreCombine() {
        return this.scoreCombine;
    }
    
    public void setScoreCombine(String scoreCombine) {
        this.scoreCombine = scoreCombine;
    }
    public String getScoreCompress() {
        return this.scoreCompress;
    }
    
    public void setScoreCompress(String scoreCompress) {
        this.scoreCompress = scoreCompress;
    }
    public String getScoreCookies() {
        return this.scoreCookies;
    }
    
    public void setScoreCookies(String scoreCookies) {
        this.scoreCookies = scoreCookies;
    }
    public String getScoreEtags() {
        return this.scoreEtags;
    }
    
    public void setScoreEtags(String scoreEtags) {
        this.scoreEtags = scoreEtags;
    }
    public String getScoreGzip() {
        return this.scoreGzip;
    }
    
    public void setScoreGzip(String scoreGzip) {
        this.scoreGzip = scoreGzip;
    }
    public String getScoreKeepAlive() {
        return this.scoreKeepAlive;
    }
    
    public void setScoreKeepAlive(String scoreKeepAlive) {
        this.scoreKeepAlive = scoreKeepAlive;
    }
    public String getScoreMinify() {
        return this.scoreMinify;
    }
    
    public void setScoreMinify(String scoreMinify) {
        this.scoreMinify = scoreMinify;
    }
    public String getScoreProgressiveJpeg() {
        return this.scoreProgressiveJpeg;
    }
    
    public void setScoreProgressiveJpeg(String scoreProgressiveJpeg) {
        this.scoreProgressiveJpeg = scoreProgressiveJpeg;
    }
    public String getServerCount() {
        return this.serverCount;
    }
    
    public void setServerCount(String serverCount) {
        this.serverCount = serverCount;
    }
    public String getServerRtt() {
        return this.serverRtt;
    }
    
    public void setServerRtt(String serverRtt) {
        this.serverRtt = serverRtt;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getTitleTime() {
        return this.titleTime;
    }
    
    public void setTitleTime(String titleTime) {
        this.titleTime = titleTime;
    }
    public String getVisualComplete() {
        return this.visualComplete;
    }
    
    public void setVisualComplete(String visualComplete) {
        this.visualComplete = visualComplete;
    }




}


