package com.hkperf;
// Generated Aug 2, 2013 12:11:08 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * Response generated by hbm2java
 */
@Entity
@Table(name = "response")
public class Response implements java.io.Serializable {


	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getWebsiteId() {
		return websiteId;
	}

	public void setWebsiteId(int websiteId) {
		this.websiteId = websiteId;
	}

	public String getTestId() {
		return testId;
	}

	public void setTestId(String testId) {
		this.testId = testId;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getRuns() {
		return runs;
	}

	public void setRuns(int runs) {
		this.runs = runs;
	}

	public Date getCreateDt() {
		return createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public int getBwDown() {
		return bwDown;
	}

	public void setBwDown(int bwDown) {
		this.bwDown = bwDown;
	}

	public int getBwUp() {
		return bwUp;
	}

	public void setBwUp(int bwUp) {
		this.bwUp = bwUp;
	}

	public Date getCompleteDate() {
		return completeDate;
	}

	public void setCompleteDate(Date completeDate) {
		this.completeDate = completeDate;
	}

	public String getConnectivity() {
		return connectivity;
	}

	public void setConnectivity(String connectivity) {
		this.connectivity = connectivity;
	}

	public String getFrm() {
		return frm;
	}

	public void setFrm(String frm) {
		this.frm = frm;
	}

	public int getLatency() {
		return latency;
	}

	public void setLatency(int latency) {
		this.latency = latency;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "request_id")
	private int id;

	@Column(name = "website_id")
	private int websiteId;

	@Column(name = "test_id")
	private String testId;
	@Column(name = "status")
	private int status;
	@Column(name = "runs")
	private int runs;
	@Column(name = "create_dt")
	private Date createDt;
	@Column(name = "bw_Down")
	private int bwDown;
	@Column(name = "bw_Up")
	private int bwUp;
	@Column(name = "complete_dt")
	private Date completeDate;
	@Column(name = "connectivity")
	private String connectivity;
	@Column(name = "frm")
	private String frm;
	@Column(name = "latency")
	private int latency;
	@Column(name = "location")
	private String location;



}


