package com.hkperf;
// Generated Aug 2, 2013 12:11:08 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ResponseViewType generated by hbm2java
 */
@Entity
@Table(name="response_view_type")
public class ResponseViewType  implements java.io.Serializable {


 
    @Id
    
    @Column(name="idresponse_view_type", unique=true, nullable=false)
    private Long idresponseViewType;
 
    
    @Column(name="view_type", length=45)
    private String viewType;
   
    public Long getIdresponseViewType() {
        return this.idresponseViewType;
    }
    
    public void setIdresponseViewType(Long idresponseViewType) {
        this.idresponseViewType = idresponseViewType;
    }
    public String getViewType() {
        return this.viewType;
    }
    
    public void setViewType(String viewType) {
        this.viewType = viewType;
    }




}


